#!/usr/bin/env bash
#SBATCH --job-name=G1_Bialyer_Basic
#SBATCH --account=XXXXX
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=32
#SBATCH --cpus-per-task=4
#SBATCH --mem=249325M
#SBATCH --time=48:00:00
#SBATCH --output=output.out

module purge
module load slurm
module load cpu
module load gcc/10.2.0
module load openmpi
module load gromacs/2019.6


export OMPI_MCA_btl=self,vader


tar xvf package.tar.gz
module purge
module load slurm
module load cpu
module load gcc/10.2.0
module load openmpi
module load gromacs/2019.6


extra_pins="-pin on -resethway"


export OMP_NUM_THREADS=4

start=6
skip=2
###################### NPT 323 500 ns 5 fs #####################################

i=$((start+skip-2))

echo $i
GRO=$i-input.gro
tpr=$((++i))-input
minim=package/nvt_1fs.mdp
top=system.top
out=$((++i))-input



mpirun -np 1 gmx_mpi grompp -f $minim  -c $GRO -p $top -o $tpr

mpirun -np $SLURM_NPROCS gmx_mpi mdrun -v -deffnm $out -s $tpr  $extra_pins


#################################################################################

###################### NPT 323 500 ns 5 fs #####################################

i=$((start+skip-0))

echo $i
GRO=$i-input.gro
tpr=$((++i))-input
minim=package/nvt_5fs.mdp
top=system.top
out=$((++i))-input



mpirun -np 1 gmx_mpi grompp -f $minim  -c $GRO -p $top -o $tpr

mpirun -np $SLURM_NPROCS gmx_mpi mdrun -v -deffnm $out -s $tpr $extra_pins


#################################################################################

###################### NPT 323 500 ns 5 fs #####################################

i=$((start+skip+2))

echo $i
GRO=$i-input.gro
tpr=$((++i))-input
minim=package/npt_5fs_long_bilayer.mdp
top=system.top
out=$((++i))-input



mpirun -np 1 gmx_mpi grompp -f $minim  -c $GRO -p $top -o $tpr

mpirun -np $SLURM_NPROCS gmx_mpi mdrun -v -deffnm $out -s $tpr  $extra_pins


#################################################################################

