#!/usr/bin/env bash

#SBATCH --account=XXXXX
#SBATCH --partition=shared
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=8
#SBATCH --time=10:00:00



tar xvf package.tar.gz



export OMPI_TMPDIR="/scratch/$USER/job_$SLURM_JOBID"

cp -r $SLURM_SUBMIT_DIR/* /scratch/$USER/job_$SLURM_JOBID/

if [ -d Outputs ]; then
  rm -r Outputs
fi
mkdir Outputs

### Change to local scratch for run
cd /scratch/$USER/job_$SLURM_JOBID

module load anaconda3/2020.11
. $ANACONDA3HOME/etc/profile.d/conda.sh
conda activate scw_test
## Please do "conda activate dcw_test" before running this script
module purge
module load slurm
module load cpu
module load gcc/10.2.0
module load openmpi
module load gromacs/2019.6

i=12
exec="mpirun -np 1 gmx_mpi"
python_exec="python"
ntomp="-ntomp 8"
export exec
export python_exec
export ntomp
export i


./VesicleX.bash


$python_exec readsolvent.py system.top


let i=i+8

return_GRO=$i-input.gro



cp /scratch/$USER/job_$SLURM_JOBID/$return_GRO $SLURM_SUBMIT_DIR/Outputs
cp /scratch/$USER/job_$SLURM_JOBID/$TOP $SLURM_SUBMIT_DIR/Outputs
cp /scratch/$USER/job_$SLURM_JOBID/$ITP $SLURM_SUBMIT_DIR/Outputs

conda deactivate 

